name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install deps
      run: go get -u github.com/gorilla/mux

    - name: Build
      run: go build -o b2watcher -v ./...

    - name: Test
      run: go test -v ./...
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled app
        path: |
          b2watcher

    